Repository bpuig/laravel-subby, pull requests merged in 2021-10, with the labels that each got.

#101 Grace period
  database/migrations/create_plan_subscriptions_table.php.stub
  database/migrations/create_plans_table.php.stub
  database/migrations/v5.0.0/alter_plan_subscriptions_table_v5.php.stub
  database/migrations/v5.0.0/alter_plans_table_v5.php.stub
  docs/v5.x/models/plan-model.md
  docs/v5.x/models/plan-subscription-model.md
  src/Models/Plan.php
  src/Models/PlanSubscription.php
  src/Traits/HasGracePeriod.php
  src/Traits/HasGracePeriodUsage.php
  src/Traits/HasSubscriptionPeriodUsage.php
  src/Traits/HasSubscriptions.php
  tests/Unit/PlanGraceTest.php
  tests/Unit/PlanSubscriptionTrialTest.php
Labels: work in progress

#103 Update docs about breaking change in syncPlan()
  docs/v5.x/install/migrate-v5.md
Labels: documentation

#96 Schedule back in main package
  config/config.php
  database/migrations/create_plan_subscription_schedules_table.php.stub
  database/migrations/v5.0.0/create_plan_subscription_schedules_table.php.stub
  docs/.vuepress/sidebar/v5.x.js
  docs/v5.x/README.md
  docs/v5.x/install/migrate-v5.md
  docs/v5.x/models/README.md
  docs/v5.x/models/plan-subscription-schedule-model.md
  src/Contracts/PlanSubscriptionScheduleService.php
  src/Jobs/SubscriptionScheduleProcessJob.php
  src/Jobs/SubscriptionScheduleQueuerJob.php
  src/Models/PlanSubscription.php
  src/Models/PlanSubscriptionSchedule.php
  src/Services/ScheduleService.php
  src/SubbyServiceProvider.php
  src/Traits/HasSchedules.php
  src/Traits/IsScheduleService.php
  tests/Services/FailedScheduleService.php
  tests/Services/SucceededScheduleService.php
  tests/TestCase.php
  tests/Unit/PlanSubscriptionScheduleTest.php
Labels: enhancement, work in progress
