Repository bpuig/laravel-subby, pull requests merged in 2021-05, with the labels that each got.

#26 Update docs
  README.md
  art/socialcard.png
Labels: documentation

#47 Subscription prorate and proportion methods separately
  src/Models/PlanSubscription.php
Labels: question

#65 canUseFeature also on trial
  src/Models/PlanSubscription.php
Labels: bug
