Repository bpuig/laravel-subby, pull requests merged in 2021-06, with the labels that each got.

#68 End trial when subscription is renewed.
  docs/v4.x/models/plan-subscription-model.md
  src/Models/PlanSubscription.php
Labels: bug

#71 use default tag while creating new subscription
  src/Traits/HasSubscriptions.php
Labels: enhancement, minor

#70 Getting the default subscription for any subscriber
  docs/v4.x/models/plan-subscription-model.md
  src/Traits/HasSubscriptions.php
Labels: enhancement, minor, question

#72 Update changelog
  docs/v4.x/CHANGELOG.md
Labels: documentation

#76 Update plan-subscription-feature-model.md
  docs/v4.x/models/plan-subscription-feature-model.md
Labels: documentation, minor

#78 Better usage handling
  docs/v5.x/models/plan-subscription-model.md
  src/Exceptions/PlanSubscriptionFeatureUsageDenied.php
  src/Models/PlanSubscription.php
Labels: bug, major, work in progress

#86 Fix getResetDate
  src/Models/PlanSubscription.php
  src/Traits/HasResetDate.php
  tests/Unit/PlanSubscriptionUsageTest.php
Labels: bug

#87 Fix reset date
  src/Traits/HasResetDate.php
Labels: bug, patch

#88 New date helper functions
  database/migrations/create_plan_subscriptions_table.php.stub
  database/migrations/v5.0.0/alter_plan_subscriptions_table_v5.php.stub
  docs/v5.x/models/plan-subscription-model.md
  src/Helpers/CarbonHelper.php
  src/Models/Plan.php
  src/Models/PlanSubscription.php
  src/Services/Period.php
  src/SubbyServiceProvider.php
  src/Traits/HasSubscriptionPeriod.php
  src/Traits/HasSubscriptionPeriodUsage.php
  src/Traits/HasSubscriptions.php
  src/Traits/HasTrialPeriod.php
  src/Traits/HasTrialPeriodUsage.php
Labels: enhancement, work in progress
